### ISSUE TITLE
Support accounts which haven't enabled 2FA

### ISSUE THREAD

**Issue by ViRb3** [SignTools/SignTools#112]
There's an additional "Do you want to enable 2FA now?" prompt that needs to be closed before login is complete.

**Comment by Joh777** [comment]
Why not open the file

**Comment by ViRb3** [comment]
I don't understand your comment in this context, please open a new issue.

**Comment by ViRb3** [comment]
Implemented in the latest update of SignTools-CI thanks to @rllbe. Can you please confirm if works for you @buitim?
