### ISSUE TITLE
A bunch of random enhancements and ideas

### ISSUE THREAD

**Issue by sourcelocation** [SignTools/SignTools#12]
Hi again,

So I thought about the features I would love to see in iOS Signer Service, and I made a list of them. So if you will have time and would like to implement those features, it would be amazing! Here's the list:

**Updated by maintainer:**
- [ ] ~~Reorder apps in list~~ - _The current order by date is sufficient in my opinion and I don't want to make the UI more complicated. Unless you have a specific use case I would prefer to keep it this way_
- [ ] ~~I can help you with this, iOS native app? :)~~ - _As discussed in private, this project will stick to a web service so it can avoid the initial sideloading problem and the one extra app slot taken in case of free dev accounts_
- [x] ~~Upload date of an app~~ - _Added in 2.0.0_
- [x] ~~Time since uploading (for apps which are still signing)~~ - _Added in 2.0.0_
- [x] ~~Drag and drop support to upload .iPA files~~ - _Added in 2.3.0_
- [x] ~~Custom name for the uploaded app on the website~~ - _Added in 2.4.4_
- [ ] Github button, which redirects to this repository
- [ ] FAQ button on top for new users
- [x] ~~Upload progress bar~~ - _Added in 2.5.10_
- [ ] Cancel signing button - _Not easily doable since not all builders provide a reference to the job via API. Would be possible to modify the signing script to periodically poll for a "cancel" request, this way we could also know exactly when the job failed instead of waiting for timeout_

**Comment by ViRb3** [comment]
I edited the comment to reflect current progress.

**Comment by yohaoquan** [comment]
I think support for uploading IPAs through url would be a great addition too

**Comment by sourcelocation** [comment]
Closing due to most things being done and everything left won't be implemented.
