### ISSUE TITLE
Git Error

### ISSUE THREAD

**Issue by SergeKZ** [SignTools/SignTools#136]
1:32PM INF using server url url=http://localhost:8080
1:32PM INF setting builder secrets
1:32PM FTL  error="get repo public key: GET https://api.github.com/repos/xxxxxx/xxxxxxx/public-key: 404 Not Found []"

help

**Comment by ViRb3** [comment]
Two problems:
1. Your server url is `localhost`. The builder (GitHub) can't reach your computer using that address.
2. Double-check your builder repo name and token. If you're getting a 404, one of the two is incorrect.

**Comment by SergeKZ** [comment]
> Two problems:
> 
> 1. Your server url is `localhost`. The builder (GitHub) can't reach your computer using that address.
> 2. Double-check your builder repo name and token. If you're getting a 404, one of the two is incorrect.
1) I want to use on localhost
2) I named the repository as login so that I wouldn't be mistaken! did not help (the error is the same
