### ISSUE TITLE
signing failed both using windows and docker

### ISSUE THREAD

**Issue by iEusKid** [SignTools/SignTools#150]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [yes ] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [yes ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

i tried both the windows option and also the docker one, both i can upload file then it will say processing.. then Failed 
tried different apps, also tried flappybird which is 2mb, i can do it through ios app signer with no issue at all

i also used revered proxy and everything is up and i can access the app through it but still the Failed issue 

logs (from the github actions)
"
Run sudo xcode-select -s /Applications/Xcode_12.5.1.app
Initializing dependencies...
Obtaining files...
Download finished!
Creating keychain...
Using provisioning profile
Extracting app...
Signing...
Using original bundle id
Preparing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmphugg2675/Payload/Flappy Bird.app
Original entitlements:
{
    "application-identifier": "GR3NL679U6.org.brandonplank.flappybird15",
    "com.apple.developer.team-identifier": "GR3NL679U6",
    "get-task-allow": true
}
ID mappings:
{
    "GR3NL679U6": "788XW9P239"
}
Removed entitlements:
[]
Processing component /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmphugg2675/Payload/Flappy Bird.app
Applying patches...
Signing
Setting CFBundleIdentifier to org.brandonplank.flappybird15
Disabled app debugging
Force enabling support for all devices
Signing with entitlements:
{
    "application-identifier": "788XW9P239.org.brandonplank.flappybird15",
    "com.apple.developer.default-data-protection": "NSFileProtectionComplete",
    "com.apple.developer.networking.networkextension": [
        "app-proxy-provider",
        "content-filter-provider",
        "packet-tunnel-provider",
        "dns-proxy",
        "dns-settings"
    ],
    "com.apple.developer.pass-type-identifiers": [
        "788XW9P239.*"
    ],
    "com.apple.developer.siri": true,
    "com.apple.developer.team-identifier": "788XW9P239",
    "com.apple.developer.ubiquity-container-identifiers": [
        "788XW9P239.*"
    ],
    "com.apple.developer.ubiquity-kvstore-identifier": "788XW9P239.*",
    "inter-app-audio": true,
    "keychain-access-groups": []
}
Waiting for any remaining components to finish signing
Packaging signed IPA...
Uploading...
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
0 0 NaN%
tus: unexpected response while creating upload, originated from request (method: POST, url: ***/jobs/5934a8c9-5260-416f-9179-84a204a0e847/tus/, response code: 301, response text: , request id: n/a)
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 27, in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('node', 'node-utils/upload.js', 'signed.ipa', '***/jobs/5934a8c9-5260-416f-9179-84a204a0e847/tus/', '***')' returned non-zero exit status 2.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 386, in <module>
    run()
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 359, in run
    node_upload(signed_ipa, f"{secret_url}/jobs/{job_id}/tus/", capture=False)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/sign.py", line 22, in node_upload
    return run_process("node", "node-utils/upload.js", str(file), endpoint, secret_key, capture=capture)
  File "/Users/runner/work/SignTools-CI/SignTools-CI/util.py", line 29, in run_process
    raise (
Exception: {'stdout': '', 'stderr': ''}
==============================================
Uploading screenshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1162k    0   133  100 1162k     92   811k  0:00:01  0:00:01 --:--:--  815k

=========================

Uploaded 1 file, 1 190 266 bytes

wget https://bashupload.com/r9VmL/test.jpg

=========================

100 1162k    0   133  100 1162k     92   811k  0:00:01  0:00:01 --:--:--  815k
==============================================
Cleaning up...
Error: Process completed with exit code 1.
"

**To reproduce**

1. Go to the site i use it in reverse proxy (and same thing without it)
2. Click on upload app
3. within 'Main" tab i choose flappybird 
4. selecting my profile and builder (github)
5. bundle identifier the 1st one then submit 

**Expected behavior**

to success and show "signed" 

**Screenshots**

**System configuration**

- SignTools version: [e.g. 2.5.11]
- Installation type: [computer(and docker tag:2.5.11 ; nginx,]
- Builder type: [SignTools-CI, ]
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commit hash of your repo for SignTools-CI, e.g. 03e0ed9]

**Additional context**

**Comment by ViRb3** [comment]
From the logs I can see the following error:

> tus: unexpected response while creating upload, originated from request (method: POST, url: /jobs/5934a8c9-5260-416f-9179-84a204a0e847/tus/, response code: 301, response text: , request id: n/a)

When the builder is uploading the signed IPA, it receives a HTTP 301 code (redirect) from your service. This should not be happening. How are you hosting the service? If it's a reverse proxy with an access control like Authelia in front, make sure that you are not protecting the public endpoints as specified by the advanced guide. Otherwise, make sure that your URL is correct. With the proper setup, there will be no 301 redirect, and the builder will be able to upload the IPA file successfully.

**Comment by iEusKid** [comment]
Hi, thanks for your reply

I actually do have Authelia but I didn’t assign it to the domain i used for signtools l.
After some trying and failing i just turned off the basic auth in the .yml file and it just worked.

Although i also did it through Herokuapp with basic auth and it worked, so i don’t really get why is that

**Comment by iEusKid** [comment]
I turned on again and used other user and password and it worked

The user and pass the caused the failing
User : iEusKid
Pass: 2R88b5Bz

**Comment by ViRb3** [comment]
I don't think the username and password values are related to the problem, but glad you got it sorted!

**Comment by ViRb3** [comment]
Just tested, the exact same credentials worked for me.
