### ISSUE TITLE
j

### ISSUE THREAD

**Issue by hggggbggjy** [SignTools/SignTools#157]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

**To reproduce**

**Expected behavior**

**Logs**

If possible, please include logs.

- For SignTools Heroku, check [how to retrieve logs via the UI](https://devcenter.heroku.com/articles/logging#log-retrieval-via-the-ui).
- For SignTools self-hosted, the logs will be printed in your terminal.
- For SignTools-CI, check [how to use workflow run logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). You can also click the "Status" button on any app in the web interface.

**Screenshots**

**System configuration**

- SignTools version: [e.g. 2.1.1]
- Installation type: [heroku, computer, phone; nginx, ngrok, cloudflared]
- Builder type: [SignTools-CI, SignTools-Builder]
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commit hash of your repo for SignTools-CI, e.g. 03e0ed9]

**Additional context**

**Comment by hggggbggjy** [comment]
<?php # : @tech4faccount  #  : @samer00s ob_start(); define('API_KEY','5043021566:AAFTixirWevYIy3impYV4AocdLqt5foW8Uw'); function bot($method,$datas=[]){     $url = "https://api.telegram.org/bot".API_KEY."/".$method; $ch = curl_init();     curl_setopt($ch,CURLOPT_URL,$url);     curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);     curl_setopt($ch,CURLOPT_POSTFIELDS,$datas);     $res = curl_exec($ch);     if(curl_error($ch)){         var_dump(curl_error($ch));     }else{         return json_decode($res);     } }  $update = json_decode(file_get_contents('php://input')); $message = $update->message; $chat_id = $message->chat->id; $text = $message->text; $chat_id2 = $update->callback_query->message->chat->id; $message_id = $update->callback_query->message->message_id; $data = $update->callback_query->data;  if($text=="/start"){ 	bot('sendmessage',[ 	'chat_id'=>$chat_id, 	'text'=>"hello", 	]); 	}

**Comment by ViRb3** [comment]
Please create a proper issue.
