### ISSUE TITLE
error: tag is needed when pushing to registry

### ISSUE THREAD

**Issue by xillscar** [SignTools/SignTools#196]
/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-BJM7xl/iidfile --label org.opencontainers.image.title=MySignTools --label org.opencontainers.image.description= --label org.opencontainers.image.url=https://github.com/***/MySignTools --label org.opencontainers.image.source=https://github.com/***/MySignTools --label org.opencontainers.image.version= --label org.opencontainers.image.created=2022-05-04T08:26:40.971Z --label org.opencontainers.image.revision=d3bfadc01c3cb6a931411f2ed7c88a9ecc16d72c --label org.opencontainers.image.licenses= --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 --secret id=GIT_AUTH_TOKEN,src=/tmp/docker-build-push-BJM7xl/tmp-2607-prlpiYPSk0LE --metadata-file /tmp/docker-build-push-BJM7xl/metadata-file --push https://github.com/***/MySignTools.git#d3bfadc01c3cb6a931411f2ed7c88a9ecc16d72c
error: tag is needed when pushing to registry
Error: buildx failed with: error: tag is needed when pushing to registry

**Comment by ViRb3** [comment]
Why are you trying to push to the Docker registry? This should only be used by the official project to create Docker images. As a user, you can just use the already created, official images.
