### ISSUE TITLE
How can I enable push notifications?

### ISSUE THREAD

**Issue by btglr** [SignTools/SignTools#209]
Hello!

Sorry to bother you again, now that I can get my apps properly signed I'm trying to get push notifications to work. I've generated a distribution certificate, signed my app with it and the app asks me if I want to enable notifications. I allowed them but I still don't get anything. I saw in [this issue](https://github.com/SignTools/SignTools/issues/96#issuecomment-903457794) that you said both the development and distribution certificates/keys are needed, so I signed the app using those again - but I still don't get push notifications.

Is there anything else I'm supposed to do?

Thanks!

**Comment by ViRb3** [comment]
You'll need a few things:
1. A clean, unmodified IPA, with all entitlements intact. I recommend dumping and decrypting it yourself using a jailbroken device. You can inject any tweaks you want through the "Advanced" tab in SignTools.

2. A p12 with both development and distribution certificate inside. To confirm if it worked, check for the following message in your builder logs:
    ```
    Using distribution certificate
    ```

**Comment by ViRb3** [comment]
> why are self-signed apps not detected the same way the original apps are in autofill

Most likely because the team id is different, and that is a part of the application id, which is what iOS uses most of the time to identify an app.

**Comment by btglr** [comment]
I see. Thanks for the help!
