### ISSUE TITLE
How can i get a .mobileprovision file?

### ISSUE THREAD

**Issue by JudiexCode** [SignTools/SignTools#211]
So I was able to get the p12 certificate from altstore, and got their password as well but, for me to able to sign any apps i would need a .mobileprovision file to do so? is there a way i can make or get one for free, Is there a tutorial to do so? Please Help Me out, Thank You

**Comment by ViRb3** [comment]
You don't need a provisioning profile with developer account, all you need is username, password, and p12.

**Comment by JudiexCode** [comment]
So after I click deploy app heroku’s website , I clicked view and this is
what it said “ Application error

An error occurred in the application and your page could not be served. If
you are the application owner, check your logs for details. You can do this
from the Heroku CLI with the command

heroku logs --tail “ is there a way to fix this? , Thank you
