### ISSUE TITLE
`xcode_archive errored`, retrying every time

### ISSUE THREAD

**Issue by CobreDev** [SignTools/SignTools#215]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Whenever I try to sign any IPA file, it always errors out at `xcode_archive errored, retrying`. I even deleted my Heroku instance and CI repo (I'm using GitHub Actions). I used to have this working, then I didn't use it for a while and it stopped working. I'm a member of an organization's paid dev account (I'm listed as the Developer role), but the Team ID in the certificate matches what's listed in the Developer portal online.

**To reproduce**

1. Go to SignTools
2. Upload IPA
3. Enter 2FA code

**Expected behavior**

I expected it to successfully sign the IPA, just like it used to.

**Logs**

If possible, please include logs.

https://pastebin.com/D931NWmz

**Screenshots**

**System configuration**

- SignTools version: v2.5.17
- Installation type: heroku
- Builder type: SignTools-CI
- Builder version: [2f3ffe4](https://github.com/SignTools/SignTools-CI/commit/2f3ffe4d8c4f2602af31de063081f1e2c2874193)

**Additional context**

**Comment by ViRb3** [comment]
> Your account does not have sufficient permissions to modify containers
Seems like you don't have sufficient permissions.

**Comment by ViRb3** [comment]
Closing since answered.
