### ISSUE TITLE
How to create a .mobileprovision file

### ISSUE THREAD

**Issue by ipasforyou** [SignTools/SignTools#234]
I manage to create the .p12 file with mac but i dont know how to create the mobileprovision file without apple developer account.

**Comment by ViRb3** [comment]
You don't need provisioning profile if you have an account.

**Comment by ipasforyou** [comment]
> You don't need provisioning profile if you have an account with p12. Check the simple guide for more information.

but in the youtube video we have to upload the base64 encoded prov.mobileprovision file

**Comment by ViRb3** [comment]
That's just one of the options demonstrated in the video. You can either use a developer account (username and password) or a .mobileprovision.

**Comment by ipasforyou** [comment]
> That's just one of the options demonstrated in the video. You can either use a developer account (username and password) or a .mobileprovision.

Is there any way to generate the mobileprovision file.
So that i can use it to sign ipas?

**Comment by ViRb3** [comment]
If you have paid developer account, then yes, you can use the developer portal. If you have free account, you can only use username and password.

**Comment by ipasforyou** [comment]
I deployed the app on heroku but it says application error
![Uploading 3DE92DB4-482E-4021-BD7F-D3A288A760F7.png…]()

**Comment by ViRb3** [comment]
https://github.com/SignTools/SignTools/blob/master/INSTALL-SIMPLE.md#5-quick-links

- [Changing existing configuration variables](https://devcenter.heroku.com/articles/config-vars#using-the-heroku-dashboard)
- [Retrieving logs via the UI](https://devcenter.heroku.com/articles/logging#log-retrieval-via-the-ui)
