### ISSUE TITLE
filed to sign everytime

### ISSUE THREAD

**Issue by MaJoRX0** [SignTools/SignTools#235]
**Logs**

Run sudo xcode-select -s /Applications/Xcode_13.2.1.app
connect ECONNREFUSED 127.0.0.1:[8](https://github.com/MaJoRX0/MAJORSIGN/runs/7891815015?check_suite_focus=true#step:3:9)080
Initializing dependencies...
Traceback (most recent call last):
  File "/Users/runner/work/MAJORSIGN/MAJORSIGN/./sign.py", line 42, in run_process
Downloading job files...
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/usr/local/Cellar/python@3.[10](https://github.com/MaJoRX0/MAJORSIGN/runs/7891815015?check_suite_focus=true#step:3:11)/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('node', 'node-utils/download.js', '***/jobs', '***', 'job.tar')' returned non-zero exit status 3.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/MAJORSIGN/MAJORSIGN/./sign.py", line [11](https://github.com/MaJoRX0/MAJORSIGN/runs/7891815015?check_suite_focus=true#step:3:12)55, in <module>
    node_download(secret_url + "/jobs", job_archive, capture=False)
  File "/Users/runner/work/MAJORSIGN/MAJORSIGN/./sign.py", line [13](https://github.com/MaJoRX0/MAJORSIGN/runs/7891815015?check_suite_focus=true#step:3:14)1, in node_download
    return run_process(
  File "/Users/runner/work/MAJORSIGN/MAJORSIGN/./sign.py", line 44, in run_process
    raise (
Exception: {'stdout': '', 'stderr': ''}
Error: Process completed with exit code 1.

**Comment by ViRb3** [comment]
> connect ECONNREFUSED 127.0.0.1:8080

You are trying to download the IPA from the builder to the builder, that's most likely incorrect. You probably want to use the service's IP/URL. See the description of `SERVER_URL` environment variable.

**Comment by MaJoRX0** [comment]
> > connect ECONNREFUSED 127.0.0.1:8080
> 
> You are trying to download the IPA from the builder to the builder, that's most likely incorrect. You probably want to use the service's IP/URL. See the description of `SERVER_URL` environment variable.

i didn't understand u I'm running it in my home server linux what did I do wrong ?
![image](https://user-images.githubusercontent.com/45786523/185419507-edeeafe6-8a9d-43e4-b0e6-8e9c499fdd28.png)

**Comment by ViRb3** [comment]
https://github.com/SignTools/SignTools/blob/master/DETAILS.md

The web service runs on your own home server. The builder runs in GitHub's CI. You have set the `server_url` to localhost, which means that the GitHub CI cannot reach your home server. You need to put a publicly reachable address of your home server there.

**Comment by MaJoRX0** [comment]
> https://github.com/SignTools/SignTools/blob/master/DETAILS.md
> 
> The web service runs on your own home server. The builder runs in GitHub's CI. You have set the `server_url` to localhost, which means that the GitHub CI cannot reach your home server (the CI will try to reach itself, because localhost). You need to put a publicly reachable address of your home server instead of localhost.

i tried to use cloudflare but it didn't work here's what i done
in my cloudflare tunnel config file
![image](https://user-images.githubusercontent.com/45786523/185429649-407f1c0a-d8cc-46e4-905a-4edc1c476078.png)
the signtools config file
![image](https://user-images.githubusercontent.com/45786523/185429758-05c519bd-e766-4bf8-b80e-2cfad3a96d08.png)
DNS settings 
![image](https://user-images.githubusercontent.com/45786523/185429853-4a79203f-8c94-4eaf-8adb-4b7a71c68190.png)
command 
![image](https://user-images.githubusercontent.com/45786523/185429890-bd02978c-deca-41c9-9b3b-1642d19b8ff4.png)

And i got i new error
`Run sudo xcode-select -s /Applications/Xcode_13.2.1.app
32256 0 0.00%
Download finished!
2121751 9357[8](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:9)14 22.67%
3408888 [9](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:10)357814 36.43%
3463395 9357814 37.01%
4407747 9357814 47.[10](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:11)%
4668996 9357814 49.89%
4678909 9357814 50.00%
7632160 9357814 81.56%
7775185 9357814 83.09%
8802291 9357814 94.06%
9320569 9357814 99.60%
9357814 9357814 100.00%
(node:15[11](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:12)) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Download finished!
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/./sign.py", line 1174, in <module>
    run()
  File "/Users/runner/work/SignTools-CI/SignTools-CI/./sign.py", line 1082, in run
    raise Exception("No development certificate found, aborting.")
Exception: No development certificate found, aborting.
==============================================
Uploading screenshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1170k    0   [13](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:14)3  100 1170k    130  1[15](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:16)0k  0:00:01  0:00:01 --:--:-- 1199k
100 1[17](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:18)0k    0   133  100 1170k    130  1150k  0:00:01  0:00:01 --:--:-- 1[19](https://github.com/MaJoRX0/SignTools-CI/runs/7901531098?check_suite_focus=true#step:3:20)9k

=========================

Uploaded 1 file, 1 198 554 bytes

wget https://bashupload.com/e2NfJ/test.jpg

=========================

==============================================
Initializing dependencies...
Downloading job files...
Downloading app...
Creating keychain...
Cleaning up...
Error: Process completed with exit code 1.`
