### ISSUE TITLE
No development certificate found

### ISSUE THREAD

**Issue by MaJoRX0** [SignTools/SignTools#236]
so cuz im using an local host server i need to use cloudflare, i tried to use cloudflare but it didn't work here's what i done

in my cloudflare tunnel config file
![image](https://user-images.githubusercontent.com/45786523/185429649-407f1c0a-d8cc-46e4-905a-4edc1c476078.png)

the signtools config file
![image](https://user-images.githubusercontent.com/45786523/185429758-05c519bd-e766-4bf8-b80e-2cfad3a96d08.png)

DNS settings 
![image](https://user-images.githubusercontent.com/45786523/185429853-4a79203f-8c94-4eaf-8adb-4b7a71c68190.png)

command 
![image](https://user-images.githubusercontent.com/45786523/185429890-bd02978c-deca-41c9-9b3b-1642d19b8ff4.png)

And i got a new error

![image](https://user-images.githubusercontent.com/45786523/185430179-323987af-f4e6-4103-814b-ddc8b05c91c5.png)

![3](https://user-images.githubusercontent.com/45786523/185435737-4637e5bd-175d-4159-8ba3-45588f6afd8a.gif)

**Comment by ViRb3** [comment]
Can you please tell me the name of your certificates as seen in Keychain? Should be something like: Apple Development ...

**Comment by MaJoRX0** [comment]
> Can you please tell me the name of your certificates as seen in Keychain? Should be something like: Apple Development ... If you are trying to use push notifications, make sure you have **both** development and distribution certificate in your p12.

![image](https://user-images.githubusercontent.com/45786523/185779394-6cec2c1c-420d-4a37-aa2e-0a60d2bbaa2f.png)

**Comment by ViRb3** [comment]
Seems like your development and distribution certificates are separate, so you need to merge them into a single p12 file, as mentioned above.

**Comment by Mabisi** [comment]
> 

How do I merge p12 certificates?

**Comment by Mabisi** [comment]
> Seems like your development and distribution certificates are separate, so you need to merge them into a single p12 file, as mentioned above.

How do I merge p12 certificates?
