### ISSUE TITLE
Install not work with reverse proxy (nginx)

### ISSUE THREAD

**Issue by xanthos84** [SignTools/SignTools#248]
**I tried basic troubleshooting first**

- [x ] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

ios 16,
trying to sign app and install,
signed succesfully through github ci,
after clicking on install on the web through iphone,
"installation starting, expect a pop up prompt" page comes up,
but then a pop up comes up:
"open this site in "itunes" ?" (cancel/open)
and after that nothing happens.

**To reproduce**

see above

**Expected behavior**

installation pop up if the ipa should be installed - but does not show.

**System configuration**

- SignTools version: [e.g. 2.1.1] 2.6.0
- Installation type: [heroku, computer, phone; nginx, ngrok, cloudflared]   phone, nginx
- Builder type: [SignTools-CI, SignTools-Builder]  signtools-ci
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commi  t hash of your repo for SignTools-CI, e.g. 03e0ed9]
newest, freshly built.

**Comment by ViRb3** [comment]
iOS 16 is fully supported. I am personally using it.

> but then a pop up comes up:
"open this site in "itunes" ?" (cancel/open)
and after that nothing happens.

Click on "Open", then another prompt will appear that asks you to install the app. If it does not, you are probably using a free developer account, which does not allow you to install apps directly from the website (OTA). For more information, check the FAQ: https://github.com/SignTools/SignTools/blob/master/FAQ.md

**Comment by xanthos84** [comment]
I am using a paid developer account.
And it was working before with my old phone, i changed now to iphone 14 pro with ios 16.0.1
and after adding new device and replacing mobile provision + p12 files on iSign,
its not working with results above.

any possibility to debug where it stops after getting the first popup?

**Comment by xanthos84** [comment]
I have made some more diagnosis, and I might know where the issue lies.
I am using a reverse proxy (nginx) with a domain to route through the app like https://my.domain.com >> IP:PORT where the app is installed. This works fine so far, but I can see that when I click on install,
the app tries to open the IP adress
https://MYIP:PORT/apps/0b404axx-d8xx-4ade-a206-5d8dcccb9fxx/manifest
instead of the domain. (beside that opening an IP with SSL https is never a good idea...? so it seems wrong anyway)

I have entered the domain in the signer-cfg.yml under "server_url"... but it seems to be ignored?

**Comment by ViRb3** [comment]
The service will take whatever URL it is called on, and use that as a base for the builder. This allows it to be very flexible under a variety of conditions. How are you doing the reverse proxy in nginx? This is most definitely a supported scenario, and it should not interfere with the request's domain.

**Comment by xanthos84** [comment]
using nginx proxy manager to reverse proxy my sites.

the config i use for that site is:

 location / {
    proxy_pass http://MYIP:30001/;
    # Force SSL
    include conf.d/include/force-ssl.conf;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;


  }

**Comment by xanthos84** [comment]
> EDIT: The above is only valid for links within the web UI. The builder will always use server_url as base.

the builder has no issues I guess, because the complete signing process works fine!
I can download the signed file through the web interface. (and also install that through altstore)
but as mentioned above, the final installation pop up does not show up.. looking for a way to debug whats happening in the background..

**Comment by ViRb3** [comment]
Gotcha. SignTools uses the request's `Host` header to build the installation URL:
https://github.com/SignTools/SignTools/blob/8c05a2d44d74aa7399d8947bd48bcb7afee8c5c5/main.go#L473-L479

This feature allows you to call it from both `http://localhost` and `https://yourwebsite.com` at the same time, and both will work.

By default, nginx will set the `Host` header to whatever is used in your `proxy_pass`, which in your case is `ip:port` and should not be used. Instead, you want to keep the `Host` header used by your browser (i.e. the domain name), so simply add this to your nginx config:
```conf
proxy_set_header Host $http_host;
```

I acknowledge that this is an easy mistake to make, so I will consider whether to document this in the docs or simply make the installation URL use `server_url` altogether, scrapping the localhost support.

**Comment by xanthos84** [comment]
good find!
that was the error! now that part is working! now i have to move on with the integration error...
thank you!

**Comment by ViRb3** [comment]
I just remembered why I did this in the first place. I wanted to support scenarios where you would have your own builder on the same LAN as your server, so you can set `server_url` to your builder's LAN IP (e.g. `http://192.168.1.101`) for very fast transfers between server <==> builder, and then you can still use a reverse proxy and expose the server publicly. Also, it's quite handy when developing locally, as you can just access localhost and have instant uploads/downloads. I will update the documentation to reflect this.
