### ISSUE TITLE
raise Exception("No development certificate found, aborting.")

### ISSUE THREAD

**Issue by itsmylife44** [SignTools/SignTools#251]
Hello. 

Deployed with heroku , imported p12 and mobileprovision from CyberChef

leaved blank the apple id and username 

this is the issue 

![immagine](https://user-images.githubusercontent.com/34112129/192651509-28d862a5-5e6c-4d43-8880-e95a184aaba1.png)

**Comment by ViRb3** [comment]
What is the content of your p12? What is the name of your certificate? It should be something like `Apple Developer: John Appleseed`.
