### ISSUE TITLE
github action failed with "no development certificate found"

### ISSUE THREAD

**Issue by abdullah5490** [SignTools/SignTools#252]
**I tried basic troubleshooting first**

- [ ] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [ ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**
I deployed signtool app via signTool-CI builder on heroku few minutes ago.  When app execute, I can see that the job name "sign" is failed under "github action" with the following log, where I've provided developer certificate and apple account credential to use for profile import during app deployment on heroku. there is no error in app on heroku but github action failed with "no developer certificate found".

**Logs**
21
(node:2347) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
22
(Use `node --trace-warnings ...` to show where the warning was created)
23
Download finished!
24
Traceback (most recent call last):
25
  File "/Users/runner/work/signtoolios/signtoolios/./sign.py", line 1173, in <module>
26
    run()
27
  File "/Users/runner/work/signtoolios/signtoolios/./sign.py", line 1081, in run
28
    raise Exception("No development certificate found, aborting.")
29
Exception: No development certificate found, aborting.

**Comment by ViRb3** [comment]
Hey. The error says it all, your p12 does not contain a developer certificate, so it cannot be used to sign. Please double check the guide on how to export a correct p12. If you are certain that your p12 is correct, please let me know the name of each item inside it.

**Comment by meelasjb** [comment]
Hi I followed these instructions to generate the P 12 file 
<!DOCTYPE html><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;"><strong style="box-sizing: border-box; font-weight: 600;">macOS</strong></p><p dir="auto" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px;">Install<span class="Apple-converted-space"> </span><a href="https://developer.apple.com/xcode/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">Xcode</a><span class="Apple-converted-space"> </span>and open the<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Account Preferences</code><span class="Apple-converted-space"> </span>(A). Sign into your account using the plus button. Select your account and click on<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Manage Certificates...</code>. In the new window (B), click the plus button and then<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Apple Development</code>. Click<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Done</code>. Now open the<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Keychain</code><span class="Apple-converted-space"> </span>app (C). There you will find your certificate and private key. Select them by holding<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Command</code>, then right-click and select<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Export 2 items...</code>. This will export you the<span class="Apple-converted-space"> </span><code style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">.p12</code>file you need.</p><table style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 16px; display: block; width: max-content; max-width: 100%; overflow: auto;"><tbody style="box-sizing: border-box; caret-color: rgb(240, 246, 252); color: rgb(240, 246, 252); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: 100%; -webkit-text-stroke-width: 0px; text-decoration: none;"><tr style="box-sizing: border-box; background-color: var(--color-canvas-default); border-top: 1px solid var(--color-border-muted);"></th></tr></tbody><br class="Apple-interchange-newline">macOS

Install [Xcode](https://developer.apple.com/xcode/) and open the Account Preferences (A). Sign into your account using the plus button. Select your account and click on Manage Certificates.... In the new window (B), click the plus button and then Apple Development. Click Done. Now open the Keychain app (C). There you will find your certificate and private key. Select them by holding Command, then right-click and select Export 2 items.... This will export you the .p12 file you need.
if I need to do anything else, please give me the link to the guide

**Comment by ViRb3** [comment]
Can you please let me know the name of each item inside your p12?

**Comment by meelasjb** [comment]
When I expand the certificate in the keychain it has Apple distribution and my name

**Comment by ViRb3** [comment]
Right. You will need **both** the development and distribution account in your p12. Re-read the guide: https://github.com/SignTools/SignTools/blob/master/INSTALL-SIMPLE.md#3-signing-profile

**Comment by abdullah5490** [comment]
in your guide, it is mention "export 2 items", and the cert file already contain 2 item, one is dev cert and second private key (with my name). I'm following the guide correctly whatever is written in it, it has no detailed info so no chance of missing something. 
I also tried using unofficial method but it doesn't work because altserver freezes after replacing DLL. 
Now, if official method is not working for me, can you please be kind enough to post some more details so that I can understand what i'm doing wrong?

**Comment by ViRb3** [comment]
From the official guide:

> Additionally, you will also need a certificate archive with a .p12 extension. It must contain **at least one certificate and at least one private key**. You can either use an Apple Development certificate, or **both Apple Development and Apple Distribution if you want to use production entitlements**. For the differences, check the [FAQ](https://github.com/SignTools/SignTools/blob/master/FAQ.md#what-kind-of-certificatesprovisioning-profiles-are-supported) page.

If you want to use distribution certificate, you need to also include your development certificate and its key in your p12. This makes 4 items in your p12. I will update the docs to make it clearer.
