### ISSUE TITLE
xcode_archive errored, retrying

### ISSUE THREAD

**Issue by wchro** [SignTools/SignTools#267]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [✓ ] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [ ✓] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

I just created my first installation, everything seemed to work until the final step generates an error "xcode_archive errored, retrying" although above I have also seen that it generates errors with the command "xcodebuild", you can see it in the logs below, I have read several old reports of similar bugs but nothing has worked for me.

**To reproduce**

1. Go to SignTools
2. Click on Upload App
3. Enter 2FA
4. Error

**Expected behavior**

Successfully signed ipa

**Logs**

https://pastebin.com/iTvRD1hT

**Screenshots**

https://i.imgur.com/N0PRXMM.png

**System configuration**

- SignTools version: 2.6.0
- Installation type: Heroku
- Builder type: SignTools-CI
- Builder version: 9d0bba6

**Additional context**

**Comment by ViRb3** [comment]
>  error: No account for team "YPYU65FUH5". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

You probably used a certificate for a different account (team). Please make sure your certificate is for this team exactly.

**Comment by wchro** [comment]
Oh thank you, working!
