### ISSUE TITLE
can not sign apps with personal developer account

### ISSUE THREAD

**Issue by asdfzxcvbn** [SignTools/SignTools#295]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

begin to sign an app with a personal developer account (p12 only), the github action will fail saying 
>  If you receive a two-factor authentication (2FA) code, please submit it to the web service.

despite me never receiving a 2fa code, and even entering one that's manually generated during the signing process. the screenshot says that the os should be updated to the latest version, and that's why it wont sign in.

**To reproduce**

1. upload app, signing with personal developer account
2. github action will fail

**Expected behavior**

the app is signed successfully, and i receieve a verification code to enter
**Logs**

If possible, please include logs.

- For SignTools Heroku, check [how to retrieve logs via the UI](https://devcenter.heroku.com/articles/logging#log-retrieval-via-the-ui).
- For SignTools self-hosted, the logs will be printed in your terminal.
- For SignTools-CI, check [how to use workflow run logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). You can also click the "Status" button on any app in the web interface.

**Screenshots**
![test3](https://user-images.githubusercontent.com/109937991/221434147-db8d6c79-1c0e-4f81-882d-9d92aa9fd332.jpg)

**System configuration**

- SignTools version: 2.6.0
- Installation type: computer, cloudflared
- Builder type: signtools-ci
- Builder version: 77ac7ae

**Additional context**

you need to update macos to sign in to xcode.

**Comment by ViRb3** [comment]
The SignTools-CI commit hash you gave does not appear to be a part of the official repository. Please update your CI to the latest version and try again.

**Comment by asdfzxcvbn** [comment]
their commit ids arent meant to match, im following the instructions and it makes an "initial commit" with that id. or maybe im just being stupid

**Comment by ViRb3** [comment]
Oh sorry, you're right, using a template will squash everything into a new commit. Anyway, please update your repo, that should be the solution to your problem.

**Comment by asdfzxcvbn** [comment]
update the repo how? i'm using the binary of the [latest release](https://github.com/SignTools/SignTools/releases/tag/v2.6.0) from september of last year

**Comment by ViRb3** [comment]
Update your repo that is a copy of SignTools-CI, not the binary.

**Comment by ViRb3** [comment]
Or actually, did you happen to enable "Advanced Data Protection for iCloud" on your account? If yes, you'll need to disable it, GitHub Actions is still running macOS 12 which does not support that option.

**Comment by asdfzxcvbn** [comment]
ohhh, yeah i do have it on. i’ll experiment with it off in a while

**Comment by ViRb3** [comment]
Hopefully this will be usable again after GitHub Actions updates to macOS 13, but only time will tell.
