### ISSUE TITLE
setup_account timed out

### ISSUE THREAD

**Issue by rllbe** [SignTools/SignTools#318]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Apple ID logging in operation timed out

**To reproduce**

1. Upload an app to the web service
2. Wait 2 minutes for the CI to process
3. See the 'Failed' text on the webpage
4. Click 'Status' button
5. View CI logs

**Expected behavior**

The 'Signed' text instead of 'Failed' text appears and the app gets signed

**Logs**

If possible, please include logs.

SignTools CI Logs
```
Run sudo xcode-select -s /Applications/Xcode_14.0.1.app
14848 0 0.00%
Download finished!
737037 14641936 5.03%
[2](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:2)[3](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:3)91655 14641936 16.33%
4231518 14641936 28.90%
5020966 14641936 34.29%
5232871 14641936 35.74%
6969262 14641936 47.60%
8927150 14641936 60.97%
9543786 14641936 65.18%
9574694 14641936 65.39%
9585120 14641936 65.46%
11902836 14641936 81.29%
12318766 14641936 84.13%
12792040 14641936 87.37%
13031842 14641936 89.00%
14634412 14641936 99.95%
14641936 14641936 100.00%
(node:1175) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Download finished!
Traceback (most recent call last):
  File "/Users/runner/work/SignTools-CI/SignTools-CI/./sign.py", line 1181, in <module>
    run()
  File "/Users/runner/work/SignTools-CI/SignTools-CI/./sign.py", line 110[4](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:4), in run
    teams = setup_account(account_name_file, account_pass_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/SignTools-CI/SignTools-CI/./sign.py", line [5](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:5)48, in setup_account
    raise Exception("Operation timed out")
Exception: Operation timed out
==============================================
Uploading screenshot...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 2[6](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:6)  608k    0     0   26  159k      0   280k  0:00:02 --:--:--  0:00:02  282k
100  608k  100    26  100  608k     24   5[7](https://github.com/rllbe/SignTools-CI/actions/runs/4995822207/jobs/8948188255#step:3:7)2k  0:00:01  0:00:01 --:--:--  575k
Could not perform prescan

==============================================
Initializing dependencies...
Downloading job files...
Downloading app...
Creating keychain...
Using development certificate
Using developer account
Logging in (1/2)...
Logging in (2/2)...
If you receive a two-factor authentication (2FA) code, please submit it to the web service.
Cleaning up...
Error: Process completed with exit code 1.
```

**Screenshots**

-

**System configuration**

- SignTools version: [e.g. 2.6.1]
- Installation type: [cloudflared]
- Builder type: [SignTools-CI]
- Builder version: [the latest commit hash of your repo for SignTools-CI, 162696f]

**Additional context**

The Apple ID does not have 2FA set up(still using security questions)

**Comment by ViRb3** [comment]
Please fill in the full template.

**Comment by ViRb3** [comment]
Also you need to submit the 2FA code you get on your phone to the web service, using the"Submit 2FA" button, otherwise it'll time out like this.

**Comment by ViRb3** [comment]
Ah, you are looking at #112 in this case. Unfortunately, accounts without 2FA are not currently supported. It should be a trivial change to the applescript files, just need to detect that 2FA is not needed and skip ahead, I just don't have such an account or the time at the moment. If you feel like you can do it, I am happy to take a PR!

**Comment by ViRb3** [comment]
Also sorry for reading between the lines of your original post, I'm on the go and didn't comprehend it properly.
