### ISSUE TITLE
Unable to get notifications working.

### ISSUE THREAD

**Issue by cam443** [SignTools/SignTools#320]
I've followed the pinned guide to try and get notifications working on Instagram v283 with Rocket v2.8.8 (and have also tried with Plus v2.50). I've used both pre-made IPAs with the tweaks already injected, and tried dumping the IPA and tweaks myself. I don't get any errors and the apps work fine, but I don't get push notifications unless the app is open/backgrounded. I also do get the `Using distribution certificate` line in the sign section. Not sure what I might be doing wrong, but would appreciate any help to go off of.

**Comment by ViRb3** [comment]
Please refer to #209. Notifications very much work. If you're still having issues, I would recommend the Discord where other users may be able to help you better.
