### ISSUE TITLE
OTA Install not working: Manifest Proxy in use despite reverse HTTPS proxy

### ISSUE THREAD

**Issue by lsc64** [SignTools/SignTools#335]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**
OTA installation fails with a Provision Profile and NGINX Reverse Proxy using HTTPs. The Webserver still shows the HTTP base-url despite actually being reachable over HTTPs and the config entry `server_url: https://{DOMAIN}`

{DOMAIN} -HTTPS> Cloudflared (Docker) -HTTPS> Nginx (Docker) -HTTP?> SignTools (Docker)

**To reproduce**

1. Use a Cloudflare Tunnel deployed in a custom docker network
2. Run Nginx in a separate container
3. Deploy a letsencrypt certificate to the nginx host {DOMAIN}
4. Setup SignTools to use `https://{DOMAIN}` and forward the nginx reverse proxy to `http://signtools:8080` with the correct proxy settings (i.e. keeping scheme)
5. Site is reachable via HTTPS. Signing works. OTA fails.

**Expected behavior**

OTA installation should succeed over the HTTPS reverse proxy.

**Logs**

`WRN using OTA manifest proxy, installation may not work base_url=http://{DOMAIN}`

**System configuration**

- SignTools version: [2.6.2](https://hub.docker.com/layers/signtools/signtools/2.6.2/images/sha256-7b73160424e38cac4fac71e1b519cfb4b1678f59535bc832f860796de65e3a9a?context=explore)
- Installation type: Cloudflared (Docker) -> Nginx (Docker) -> SignTools (Docker)
- Builder type: SignTools-CI
- Builder version: [5148bc4](https://github.com/SignTools/SignTools-CI/commit/5148bc4296c4ba583b0444945d621efd150f11c9)

**Question**
How do we make SignTools aware that it's begin accessed via https? Or is something truly misconfigured?

**Comment by ViRb3** [comment]
Yes, this is because nginx reverse proxies the  request over HTTP and completely hides the fact that HTTPS was used by thr client. To fix, make sure you add the special "hint" headers as specified in the guide: https://github.com/SignTools/SignTools/blob/master/INSTALL-ADVANCED.md#4a-reverse-proxy
