### ISSUE TITLE
Multiple teams found on the Developer Portal error

### ISSUE THREAD

**Issue by mgcrea** [SignTools/SignTools#399]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

When trying to resign, I get the following error on the CI just after the step `Registering component with Apple...`:

```
Multiple teams found on the Developer Portal, Your Terminal is running in non-interactive mode! Cannot continue from here.\nPlease check that you set FASTLANE_TEAM_ID or FASTLANE_TEAM_NAME to the right value.
```

Any ideas?

**System configuration**

- SignTools version: 3.0.1
- Installation type: cloudflared
- Operating System: macOS
- Builder type: SignTools-CI
- Builder version: 14220bc

**Additional context**

**Comment by markrassamni** [comment]
Here is how I solved this issue when I had it

In sign.py line 373 add this:

```diff
def fastlane_register_app(account_name: str, account_pass: str, bundle_id: str, entitlements: Dict[Any, Any]):
    my_env = os.environ.copy()
    my_env["FASTLANE_USER"] = account_name
    my_env["FASTLANE_PASSWORD"] = account_pass
+   my_env["FASTLANE_TEAM_ID"] = os.path.expandvars("$FASTLANE_TEAM_ID")
```

In .github/workflows/sign.yml add the value to your env at line 13

```diff
    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"
+     FASTLANE_TEAM_ID: "${{ vars.FASTLANE_TEAM_ID }}"      
```

Then in your project go to Settings > Secrets and Variables > Actions > Variables
Add a key `FASTLANE_TEAM_ID` with the value of your team ID

You could modify the code to work with secrets if you prefer.

**Comment by ViRb3** [comment]
This looks like something we will have to surface to the `config.yml` file. I don't have time now, but will try to look at this soon.

**Comment by ViRb3** [comment]
Pushed a fix in: https://github.com/SignTools/SignTools-CI/commit/283a82bf2e9ff8b3176b886c74eee4fdcc209ba4

Update your SignTools-CI and you should be good to go.

**Comment by mgcrea** [comment]
@ViRb3 can confirm that it works and I no longer get the same error, unfortunately signing still does fail at a later stage `Signing with entitlements:`, but it does not look like it is related. Thanks for the help/patch!

```
subprocess.CalledProcessError: Command '('fastlane', 'produce', 'create', '--skip_itc', '--app_identifier', 'com.foo.bar.baz.mgcrea', '--app-name', 'ST com foo bar baz mgcrea')' returned non-zero exit status 1.
```

**Comment by ViRb3** [comment]
There should be more detailed logs from fastlane that tell you exactly what's wrong. If I were to guess, maybe the bundle id `com.foo.bar.baz.mgcrea` is already taken by a different dev account.

**Comment by mgcrea** [comment]
> There should be more detailed logs from fastlane that tell you exactly what's wrong. If I were to guess, maybe the bundle id `com.foo.bar.baz.mgcrea` is already taken by a different dev account.

Unfortunately the output is truncated and stops abruptly:

```
[21:26:31]: Creating new app 'ST com foo bar baz mgcrea' on the Apple Dev Center\n\nLooking for related GitHub issues on fastlane/fastlane...\n\nFound no similar issues. To crea
Cleaning up...
```

But you might be onto something about the ID being taken as I've signed with another team in the past, will retry! Thanks!

**Comment by mgcrea** [comment]
@ViRb3 That was it! It finally worked, thanks!
