### ISSUE TITLE
Discord link is not working

### ISSUE THREAD

**Issue by markrassamni** [SignTools/SignTools#400]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Discord invite link no longer works. I am also no longer in the server. Was the server closed?

**To reproduce**

1. Click invite link from readme [https://discord.gg/A4T6npnRCk](https://discord.gg/A4T6npnRCk)
2. Receive message Invite Invalid

**Expected behavior**

Be able to join the server

**Comment by ViRb3** [comment]
Ah yes, I closed the Discord server since it didn't have much activity and I didn't have time to check or moderate it. GitHub is better suited for tracking issues, so let's stick to here. I will update the docs to remove the invite link.
