### ISSUE TITLE
OTA Manifest error when on https

### ISSUE THREAD

**Issue by Anime-Forevere** [SignTools/SignTools#410]
**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

When trying to install an app from the signtools (hosted locally and exposed through reverse proxy Nginx Proxy Manager) I get `using OTA manifest proxy, installation may not work`. The url that I access my instance of signtools is `https://sign.xxx.com` (where xxx is my domain name), but it reports that it sets `base_url` to `http://sign.xxx.com` (`WRN using OTA manifest proxy, installation may not work base_url=http://sign.xxx.com`)

**To reproduce**

1. Go to the self hosted instance of signtools
2. Upload the app and wait for it to be signed
3. Install the app

**Expected behavior**

A `Do you want to install this app?` prompt appears and app installs

**Logs**

* In logs, url is replaced with `sign.xxx.com` and ips are replaced with `xxx.xxx.xxx.xxx` for my own safety
[_signtools_logs.txt](https://github.com/SignTools/SignTools/files/14686582/_signtools_logs.txt)

**Screenshots**

None.

**System configuration**

- SignTools version: [e.g. 3.0.0]  v3.0.2
- Installation type: [cloud server, personal computer; nginx, ngrok, cloudflared] Personal Computer, Nginx Proxy Manager
- Operating System: [macOS, Linux, Windows] Linux, Debian 11 (signtools is running in docker container using `signtools/signtools`)
- Builder type: [SignTools-CI, SignTools-Builder] SignTools-CI
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commit hash of your repo for SignTools-CI, e.g. 03e0ed9] 13250eb

**Comment by ViRb3** [comment]
You need to pass the `X-Forwarded-Proto: https` header from your reverse proxy to SignTools, see https://github.com/SignTools/SignTools/blob/master/INSTALL.md#4a-reverse-proxy.

**Comment by Anime-Forevere** [comment]
> You need to pass the `X-Forwarded-Proto: https` header from your reverse proxy to SignTools, see https://github.com/SignTools/SignTools/blob/master/INSTALL.md#4a-reverse-proxy.

It is already done by NPM (Nginx Proxy Manager), so it doesn't seem to be the problem. Any other solution?
![image](https://github.com/SignTools/SignTools/assets/56559528/829527d1-46ba-415f-a721-3b21ded0c3e0)

**Comment by ViRb3** [comment]
I can think of a few potential issues:
- `$scheme` is not https; maybe try hardcoding `https` instead of `$scheme` just to test?
- is there something else in front of SignTools?
- is there something in front of nginx?
- what's in `proxy.conf`? maybe it's overriding something?

**Comment by Anime-Forevere** [comment]
>     * `$scheme` is not https; maybe try hardcoding `https` instead of `$scheme` just to test?

Looks like when I set it to `https`, I can't access the service at all. Also, when I set `Automatically redirect to https` in config, 
I start receiving `SSL received a record that exceeded the maximum permissible length.` when visiting signtools directly (through local ip and port). Possibly this is the issue with `https` scheme.

**Comment by ViRb3** [comment]
The `X-Forwarded-Proto` is only used by SignTools for manifest creation and `Automatically redirect to https`, if enabled. If SignTools doesn't work at all, you probably have something else in the middle that breaks. I imagine the second error you get is due to infinite redirection if SignTools never sees `https` in the `X-Forwarded-Proto` header. Either way, seems like a problem with your setup.
