### ISSUE TITLE
[Question] How does the  Use provisioning profile's application ID work?

### ISSUE THREAD

**Issue by officiallor** [SignTools/SignTools#453]
Hello
I wanted to try to fix the dynamic island not working as in the original apps and I found SignTools. I managed to set it up in a few minutes although I have some suggestions about this.
My question is how does the use provisioning profile's application ID work? This option worked for me but it says that I won't be able to install another app because it has a fixed id which I verified it myself. 
Is there any way to fix the dynamic island for more than one app?

Regarding the setup process, I would like to suggest and I might try when I find some time to write a tutorial, after I figure out how to make it work as I haven't done such a setup for locally running the build process. It would be easier for most of the people that want to use SignTools to run it locally even if it will require a couple of extra steps.

**Comment by ViRb3** [comment]
This should explain it pretty well: https://github.com/SignTools/SignTools/blob/master/FAQ.md#2-provisioning-profiles

Let me know if you still have any questions after reading.

**Comment by officiallor** [comment]
When I use the use profile's application id, I get something like com.fixedTextHere.explicit so I guess it's a explicit one. I don't know any other way to check though. 
I am signing other apps too but as the link says probably it's improperly signed and some features may not work. 
Isn't there any way to bypass this limitation? 
Is there any specific reason that the explicit are more widespread? Something like a limitation for providing one for many users through the apple developer account?
