### ISSUE TITLE
R

### ISSUE THREAD

**Issue by CIPIYCCC** [SignTools/SignTools#484]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [ ] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [ ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

**To reproduce**

**Expected behavior**

**Logs**

If possible, please include logs.

- For SignTools, the logs will be printed in your terminal.
- For SignTools-CI, check [how to use workflow run logs](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). You can also click the "Status" button on any app in the web interface.

**Screenshots**

**System configuration**

- SignTools version: [e.g. 3.0.0]
- Installation type: [cloud server, personal computer; nginx, ngrok, cloudflared]
- Operating System: [macOS, Linux, Windows]
- Builder type: [SignTools-CI, SignTools-Builder]
- Builder version: [e.g. 1.0.0 for SignTools-Builder; the latest commit hash of your repo for SignTools-CI, e.g. 03e0ed9]

**Additional context**

**Comment by ViRb3** [comment]
Template is empty, assuming this was a mistake.
