### ISSUE TITLE
Sign.py not functioning properly

### ISSUE THREAD

**Issue by Kaspeck** [SignTools/SignTools#491]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [ Yes] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [Yes ] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**

Sign.py is not running.

**To reproduce**

1. Upload ipa on localhost
2. Check github actions
3. See Error

**Expected behavior**

I expect the build to pass.

**Logs**

If possible, please include logs.

Run PYTHONUNBUFFERED=1 ./sign.py
Initializing dependencies...
Downloading job files...

Traceback (most recent call last):
  File "/Users/runner/work/Signtools-CI/Signtools-CI/./sign.py", line 45, in run_process
    result = subprocess.run(cmd, capture_output=capture, check=check, env=env, cwd=cwd, timeout=timeout)
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 5[7](https://github.com/Kaspeck/Signtools-CI/actions/runs/11879799313/job/33102159672#step:4:8)7, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('node', 'node-utils/download.js', '***/jobs', '***', 'job.tar')' returned non-zero exit status 3.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/runner/work/Signtools-CI/Signtools-CI/./sign.py", line [12](https://github.com/Kaspeck/Signtools-CI/actions/runs/11879799313/job/33102159672#step:4:13)54, in <module>
    node_download(secret_url + "/jobs", job_archive, capture=False)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/Signtools-CI/Signtools-CI/./sign.py", line 122, in node_download
    return run_process(
        "node",
    ...<4 lines>...
        capture=capture,
    )
  File "/Users/runner/work/Signtools-CI/Signtools-CI/./sign.py", line 47, in run_process
    raise (
    ...<6 lines>...
    ) from e
Exception: {'stdout': '', 'stderr': ''}
Error: Process completed with exit code 1.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**System configuration**

- SignTools version: 3.05
- Installation type: [cloud server, personal computer; nginx, ngrok, cloudflared]
- Operating System: Windows
- Builder type: Signtools-CI
- Builder version: 695a927

**Additional context**

Add any other context about the problem here.

**Comment by ViRb3** [comment]
> Installation type: [cloud server, personal computer; nginx, ngrok, cloudflared]

You didn't specify how you are running this. If I had to guess, GitHub can't reach the service running on your localhost. You either need to expose a port and set up a reverse proxy, or use a tunnel provider like ngrok/cloudflared.

**Comment by ViRb3** [comment]
Regarding the lack of error message, this was a bug and I just pushed out a fix for that in SignTools-CI. If you update your repo and try again, you should see the exact error, which will likely be what I mentioned above.
