### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by J2TR1PPY** [SignTools/SignTools#508]
can someone please help me with installing this on windows i am very confused i've configured the file to suit the builder i am going to be using and i've put the files in the folder im using a mobile provision file and certificate but i can't seem to find the next step of what to do i can't understand can someone please help me in a detailed manner

**Comment by ViRb3** [comment]
> i can't seem to find the next step of what to do

Once you have configured everything, just run the SignTools server, then navigate to the corresponding IP address and port that you configured. The SignTools UI is entirely web based, so all usage happens in a browser.

**Comment by J2TR1PPY** [comment]
> > i can't seem to find the next step of what to do
> 
> 
> 
> Once you have configured everything, just run the SignTools server, then navigate to the corresponding IP address and port that you configured. The SignTools UI is entirely web based, so all usage happens in a browser.

how do i run the sign tools server? i've so far done this can you help ![image](https://github.com/user-attachments/assets/72f44eec-03a3-45dd-97a3-cf2b33c6ea4e)[image](https://github.com/user-attachments/assets/cd6ba48b-ba2c-49e3-81e0-654e47ce80de)

**Comment by J2TR1PPY** [comment]
i'm not sure which of these web service executions to do i've  also done this![image](https://github.com/user-attachments/assets/5a52e24f-c9be-4cf1-a39f-c2037331bb00)

**Comment by ViRb3** [comment]
I removed your config picture for privacy since it contained your GitHub API token. Please change it ASAP.

To start the server, just run [SignTools_3.0.5_windows_amd64.exe](https://github.com/SignTools/SignTools/releases/download/v3.0.5/SignTools_3.0.5_windows_amd64.exe) or equivalent for your operating system.

**Comment by J2TR1PPY** [comment]
okay thank you when i try and run it it doesn't do anything it just exits

**Comment by ViRb3** [comment]
Run it from Terminal / Command Prompt, that way any message it prints won't immediately disappear. It probably exits due to an error.

**Comment by J2TR1PPY** [comment]
how do i explicitly select sign tools to run in cmd

**Comment by ViRb3** [comment]
https://www.wikihow.com/Run-a-Program-on-Command-Prompt

**Comment by J2TR1PPY** [comment]
this is what i get ![image](https://github.com/user-attachments/assets/98a82b8d-1478-403f-a3a7-54be24b58267)

**Comment by ViRb3** [comment]
You need two separate commands, try:
```
cd C:\Users\Azeem\Downloads
start SignTools_3.0.5_windows_amd64
```

**Comment by J2TR1PPY** [comment]
it just sits there when i enter it![image](https://github.com/user-attachments/assets/c081f834-7382-4f4d-8854-c4e3fdc1c46e)

**Comment by ViRb3** [comment]
Can you try without `start`? Just `SignTools_3.0.5_windows_amd64`.

**Comment by J2TR1PPY** [comment]
that seems to give me this error [image](https://github.com/user-attachments/assets/e25e9da3-7822-4336-be85-4148b355bc47)

**Comment by ViRb3** [comment]
Cool, this is some progress. You need to follow the file names exactly. Your .p12 file is named "krava39", it needs to be named cert.p12.

**Comment by J2TR1PPY** [comment]
i've changed all of them to match however i'm still getting the same error

**Comment by ViRb3** [comment]
I noticed your Windows settings hide the file extensions by default. If you type "cert.p12" and the file type is already p12, you will end up with "cert.p12.p12", which is invalid. Please enable the setting to show file extensions and make sure they align with that on.

https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/How-to-enable-hidden-file-extensions-in-Windows.html

**Comment by J2TR1PPY** [comment]
thank you this is where it stops now [image](https://github.com/user-attachments/assets/b3bcaf8d-5ec1-42ed-9e3c-310c3036be74)

**Comment by ViRb3** [comment]
You can now access the web UI by opening http://localhost:8080 in your browser.

Note however, from the config you showed before, signing will NOT work. As written in the docs, the address you put in "server_url" needs to be reachable by the builder. You have put localhost there, which means the builder (GitHub's server) will just try to connect to itself, which won't work. You need to expose your computer's port 8080 to the builder somehow. Read section "4b. Tunnel provider" carefully, it describes an easy way to do that.

**Comment by J2TR1PPY** [comment]
does this mean that it has worked ![image](https://github.com/user-attachments/assets/b5577274-4597-48aa-8e46-730304696259)

**Comment by J2TR1PPY** [comment]
it shows me this ![image](https://github.com/user-attachments/assets/1a7d0bc3-ecb9-444a-8cb1-f5c1b67a4fbf)

**Comment by bostok8** [comment]
I think I'm getting the same error 401. Did you solve it?

<img width="656" alt="Unrecognized code signing certificate" src="https://github.com/user-attachments/assets/967c1f89-eae9-4f55-9969-06cb749dac55" />

**Comment by J2TR1PPY** [comment]
> I think I'm getting the same error 401. Did you solve it?
> 
> 
> 
> <img width="656" alt="Unrecognized code signing certificate" src="https://github.com/user-attachments/assets/967c1f89-eae9-4f55-9969-06cb749dac55" />
> 
> 

nope i didn't get any further help but i was trying to get a side loaded app to work like a normal app in terms of ios widgets and i found one way to make it work

**Comment by bostok8** [comment]
> > I think I'm getting the same error 401. Did you solve it?
> > <img alt="Unrecognized code signing certificate" width="656" src="https://private-user-images.githubusercontent.com/62780323/399275512-967c1f89-eae9-4f55-9969-06cb749dac55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NTcyMTcsIm5iZiI6MTczNTU1NjkxNywicGF0aCI6Ii82Mjc4MDMyMy8zOTkyNzU1MTItOTY3YzFmODktZWFlOS00ZjU1LTk5NjktMDZjYjc0OWRhYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDExMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2NGQxMjk1NThjMmU3YWQ5YTIwNWU2ODdhZmFmNWQ4NDUyMjE5MWIzNWFmY2I0NWNjMDViOGZiNGM1ZmEwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z341cBBbG2GK58YBPV4oyjnJGjQmoVESX2cDw783gB0">
> 
> nope i didn't get any further help but i was trying to get a side loaded app to work like a normal app in terms of ios widgets and i found one way to make it work

That's what I need too. How did you make it?

**Comment by bostok8** [comment]
> I think I'm getting the same error 401. Did you solve it?
> <img alt="Unrecognized code signing certificate" width="656" src="https://private-user-images.githubusercontent.com/62780323/399275512-967c1f89-eae9-4f55-9969-06cb749dac55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDM0NDUsIm5iZiI6MTczNTYwMzE0NSwicGF0aCI6Ii82Mjc4MDMyMy8zOTkyNzU1MTItOTY3YzFmODktZWFlOS00ZjU1LTk5NjktMDZjYjc0OWRhYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDIzNTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjVjMzFhYzY0Yzc2Y2YzMTk0MWJmMzRmN2Y0MGI1MWQxMDQ0NDQ4NjI0MjZiNGYyMWNhNTlkMTNmNDVhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea9B4sos-yYOGdfU3D3M87WCq96A6hTxq5DJAEoTEhQ">

I realized the certificate wasn't right. I made it work following these steps:
https://gist.github.com/boodle/77436b2d9facb8e938ad
Take into account after 6. it's necessary rename "development.cer" to "ios_enterprise.cer."

So, I solve this problem, but anyway, I can't activate Carplay in the app because I don't have Carplay entitlements... (https://developer.apple.com/documentation/carplay/requesting-carplay-entitlements)

**Comment by J2TR1PPY** [comment]
> > I think I'm getting the same error 401. Did you solve it?
> 
> > <img alt="Unrecognized code signing certificate" width="656" src="https://private-user-images.githubusercontent.com/62780323/399275512-967c1f89-eae9-4f55-9969-06cb749dac55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDM0NDUsIm5iZiI6MTczNTYwMzE0NSwicGF0aCI6Ii82Mjc4MDMyMy8zOTkyNzU1MTItOTY3YzFmODktZWFlOS00ZjU1LTk5NjktMDZjYjc0OWRhYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDIzNTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjVjMzFhYzY0Yzc2Y2YzMTk0MWJmMzRmN2Y0MGI1MWQxMDQ0NDQ4NjI0MjZiNGYyMWNhNTlkMTNmNDVhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea9B4sos-yYOGdfU3D3M87WCq96A6hTxq5DJAEoTEhQ">
> 
> 
> 
> I realized the certificate wasn't right. I made it work following these steps:
> 
> https://gist.github.com/boodle/77436b2d9facb8e938ad
> 
> Take into account after 6. it's necessary to rename "development.cer" to "ios_enterprise.cer."
> 
> 
> 
> So, I solve this problem, but anyway, I can't activate Carplay in the app because I don't have Carplay entitlements... (https://developer.apple.com/documentation/carplay/requesting-carplay-entitlements)

i presume we need a developer account to make it use the entitlements of carplay and then we needa write it in ourselves i think the same applies for siri

**Comment by bostok8** [comment]
> > > I think I'm getting the same error 401. Did you solve it?
> > 
> > 
> > > <img alt="Unrecognized code signing certificate" width="656" src="https://private-user-images.githubusercontent.com/62780323/399275512-967c1f89-eae9-4f55-9969-06cb749dac55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDM0NDUsIm5iZiI6MTczNTYwMzE0NSwicGF0aCI6Ii82Mjc4MDMyMy8zOTkyNzU1MTItOTY3YzFmODktZWFlOS00ZjU1LTk5NjktMDZjYjc0OWRhYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDIzNTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjVjMzFhYzY0Yzc2Y2YzMTk0MWJmMzRmN2Y0MGI1MWQxMDQ0NDQ4NjI0MjZiNGYyMWNhNTlkMTNmNDVhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea9B4sos-yYOGdfU3D3M87WCq96A6hTxq5DJAEoTEhQ">
> > 
> > 
> > I realized the certificate wasn't right. I made it work following these steps:
> > https://gist.github.com/boodle/77436b2d9facb8e938ad
> > Take into account after 6. it's necessary to rename "development.cer" to "ios_enterprise.cer."
> > So, I solve this problem, but anyway, I can't activate Carplay in the app because I don't have Carplay entitlements... (https://developer.apple.com/documentation/carplay/requesting-carplay-entitlements)
> 
> i presume we need a developer account to make it use the entitlements of carplay and then we needa write it in ourselves i think the same applies for siri

you also have to submit a form explaining why you need access to Carplay. So, a developer account is not enough...

**Comment by J2TR1PPY** [comment]
> > > > I think I'm getting the same error 401. Did you solve it?
> 
> > > 
> 
> > > 
> 
> > > > <img alt="Unrecognized code signing certificate" width="656" src="https://private-user-images.githubusercontent.com/62780323/399275512-967c1f89-eae9-4f55-9969-06cb749dac55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDM0NDUsIm5iZiI6MTczNTYwMzE0NSwicGF0aCI6Ii82Mjc4MDMyMy8zOTkyNzU1MTItOTY3YzFmODktZWFlOS00ZjU1LTk5NjktMDZjYjc0OWRhYzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDIzNTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjVjMzFhYzY0Yzc2Y2YzMTk0MWJmMzRmN2Y0MGI1MWQxMDQ0NDQ4NjI0MjZiNGYyMWNhNTlkMTNmNDVhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ea9B4sos-yYOGdfU3D3M87WCq96A6hTxq5DJAEoTEhQ">
> 
> > > 
> 
> > > 
> 
> > > I realized the certificate wasn't right. I made it work following these steps:
> 
> > > https://gist.github.com/boodle/77436b2d9facb8e938ad
> 
> > > Take into account after 6. it's necessary to rename "development.cer" to "ios_enterprise.cer."
> 
> > > So, I solve this problem, but anyway, I can't activate Carplay in the app because I don't have Carplay entitlements... (https://developer.apple.com/documentation/carplay/requesting-carplay-entitlements)
> 
> > 
> 
> > i presume we need a developer account to make it use the entitlements of carplay and then we needa write it in ourselves i think the same applies for siri
> 
> 
> 
> you also have to submit a form explaining why you need access to Carplay. So, a developer account is not enough...

you need a developer account then explaining why you need it which is already quite long but the first step would be to have a developer account im pretty sure so you can request the entitlements

**Comment by coolopj** [comment]
Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks

**Comment by J2TR1PPY** [comment]
> Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks

i personally don't know but is that how it works?

**Comment by coolopj** [comment]
> > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> 
> i personally don't know but is that how it works?

I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.

**Comment by J2TR1PPY** [comment]
> > > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> 
> > 
> 
> > i personally don't know but is that how it works?
> 
> 
> 
> I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.

then i feel using the alphanumeric code at the end is the way to get the apps to work in harmony w ios and not fight over eachother because when trying todo it manually only one app can make use of all ios features as others would try replace it i dont know how signtools and others make it work but they make it work with that last bit after the bundle id to specify it to work with ios for your device

**Comment by coolopj** [comment]
> > > > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> > 
> > 
> > > 
> > 
> > 
> > > i personally don't know but is that how it works?
> > 
> > 
> > I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.
> 
> then i feel using the alphanumeric code at the end is the way to get the apps to work in harmony w ios and not fight over eachother because when trying todo it manually only one app can make use of all ios features as others would try replace it i dont know how signtools and others make it work but they make it work with that last bit after the bundle id to specify it to work with ios for your device

if signtools could follow the pattern of sideloady it would have been the best of the best app to sign ipa because with signtools, apps installation is not limited to just 3 apps and it's taking forever for Sideloadly to add support for Dev cert.

**Comment by J2TR1PPY** [comment]
> > > > > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > i personally don't know but is that how it works?
> 
> > > 
> 
> > > 
> 
> > > I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.
> 
> > 
> 
> > then i feel using the alphanumeric code at the end is the way to get the apps to work in harmony w ios and not fight over eachother because when trying todo it manually only one app can make use of all ios features as others would try replace it i dont know how signtools and others make it work but they make it work with that last bit after the bundle id to specify it to work with ios for your device
> 
> 
> 
> if signtools could follow the pattern of sideloady it would have been the best of the best app to sign ipa because with signtools, apps installation is not limited to just 3 apps and it's taking forever for Sideloadly to add support for Dev cert.

i hope they follow suit soon i've been waiting for that feature for quite some time and with a little help it'd be the best of both worlds or both side i mean

**Comment by coolopj** [comment]
> > > > > > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > i personally don't know but is that how it works?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.
> > 
> > 
> > > 
> > 
> > 
> > > then i feel using the alphanumeric code at the end is the way to get the apps to work in harmony w ios and not fight over eachother because when trying todo it manually only one app can make use of all ios features as others would try replace it i dont know how signtools and others make it work but they make it work with that last bit after the bundle id to specify it to work with ios for your device
> > 
> > 
> > if signtools could follow the pattern of sideloady it would have been the best of the best app to sign ipa because with signtools, apps installation is not limited to just 3 apps and it's taking forever for Sideloadly to add support for Dev cert.
> 
> i hope they follow suit soon i've been waiting for that feature for quite some time and with a little help it'd be the best of both worlds or both side i mean

Wish this could be push forward to the devs of the Signtools maybe they can find a workaround.

**Comment by J2TR1PPY** [comment]
> > > > > > > Great work! I really enjoy using the app. I want to ask if it's possible for signtools to sign ipa using the option [Use provisioning profile's application ID] the way Sideloadly does by adding the explicit provisional profile after the real bundle ID for example ,  com.spotify.client.C5678X786. with that more than one app can be installed at once using the option. Thanks
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > i personally don't know but is that how it works?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > I think that's how it works because app signed with signtools using the option provisional profile has a unique bundle ID  that's why it can't support multiple apps installation because there is no difference, it will definitely override the app previously installed  because they both has the same Bundle ID. I've installed three apps using sideloady and they never override each other  but they have thesame alphanumeric unique code at the of the real bundle ID like  I indicated earlier and they work perfectly and can be launched from Lock Screen and dynamic island.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > then i feel using the alphanumeric code at the end is the way to get the apps to work in harmony w ios and not fight over eachother because when trying todo it manually only one app can make use of all ios features as others would try replace it i dont know how signtools and others make it work but they make it work with that last bit after the bundle id to specify it to work with ios for your device
> 
> > > 
> 
> > > 
> 
> > > if signtools could follow the pattern of sideloady it would have been the best of the best app to sign ipa because with signtools, apps installation is not limited to just 3 apps and it's taking forever for Sideloadly to add support for Dev cert.
> 
> > 
> 
> > i hope they follow suit soon i've been waiting for that feature for quite some time and with a little help it'd be the best of both worlds or both side i mean
> 
> 
> 
> Wish this could be push forward to the devs of the Signtools maybe they can find a workaround.

hopefully one of the devs can see this and possibly implement it

**Comment by ViRb3** [comment]
This is getting off topic from the original issue. Can you please create a separate issue for the feature request and describe it in full detail? I'm happy to look into a new identifier naming scheme if it would be truly useful.

**Comment by ViRb3** [comment]
I'm closing this one as resolved since the original issue was answered. Feel free to create a new one if you have additional questions or issues.
